image: lpmn/lalsuite:minke-latest

stages:
  - test
  - build
#  - deploy

test:
  stage: test
  script:
    - python setup.py test
  # As a temporary measure
  allow_failure: true


pages:
  stage: build
  script:
  - pip install sphinx sphinx-bootstrap-theme numpydoc # sphinxcontrib-versioning
  - make docs
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master


# Build receipe for standalone wheels on Linux
build:wheel:
  stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py bdist_wheel --universal
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - wheelhouse



# deploy:wheel:
#    stage: deploy
#    image: containers.ligo.org/lscsoft/lalsuite-manylinux:master
#    script:
#     - /opt/python/cp36-cp36m/bin/pip install twine	
#     - /opt/python/cp36-cp36m/bin/twine upload wheelhouse/*

#   artifacts:
#     expire_in: 3h
#     paths:
#       - wheelhouse
#   only:
#     - master@lscsoft/lalsuite
#   except:
#     - pushes
#     - web