image: lpmn/lalsuite:minke-latest

test:
  script:
    - python setup.py test


build:pages:
  script:
  - pip install sphinx sphinx-bootstrap-theme numpydoc
  - make docs
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master


# Build receipe for standalone wheels on Linux
build:wheel:
  # This container is derived from the official manylinux image provided by
  # python.org (see PEP 513), and includes all of the LALSuite
  # build-dependencies.
  # stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py bdist_wheel --universal
    # Bundle and fix up dependent shared libraries
    - auditwheel repair wheel/*.whl
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - wheelhouse



# deploy:wheel:
#    stage: deploy
#    image: containers.ligo.org/lscsoft/lalsuite-manylinux:master
#    script:
#     - /opt/python/cp36-cp36m/bin/pip install twine	
#     - /opt/python/cp36-cp36m/bin/twine upload wheelhouse/*

#   artifacts:
#     expire_in: 3h
#     paths:
#       - wheelhouse
#   only:
#     - master@lscsoft/lalsuite
#   except:
#     - pushes
#     - web